"""add auth fields to users

Revision ID: 0c52f02cc87a
Revises: 7340daf7a216
Create Date: 2026-09-22 13:33:33.032567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c52f02cc87a'
down_revision: Union[str, Sequence[str], None] = '7340daf7a216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('DRIVER', 'OWNER', 'ADMIN', name='user_role')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('apartment_number', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('role', user_role_enum, server_default='DRIVER', nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'apartment_number')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###

    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
