"""add spot overrides table

Revision ID: 3795dae0e113
Revises: d4770c942b3c
Create Date: 2026-09-25 15:00:45.742693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3795dae0e113'
down_revision: Union[str, Sequence[str], None] = 'd4770c942b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_override',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('spot_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'BUSY', name='override_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id', 'date', 'start_time', 'end_time', name='uq_override_spot_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_override')
    # ### end Alembic commands ###
