"""add spot notes and rejection reason

Revision ID: 3fa4d7793180
Revises: d4fdcb484196
Create Date: 2026-09-25 15:25:53.680414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa4d7793180'
down_revision: Union[str, Sequence[str], None] = 'd4fdcb484196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('spot', sa.Column('rejection_reason', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###

    # Alembic's autogenerate does not detect new enum members, so this is added by hand.
    op.execute("ALTER TYPE reservation_status ADD VALUE IF NOT EXISTS 'CANCELLED_BY_ADMIN'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot', 'rejection_reason')
    op.drop_column('spot', 'notes')
    # ### end Alembic commands ###
