"""add cars table

Revision ID: aab880f8b03e
Revises: 0c52f02cc87a
Create Date: 2026-09-22 16:59:49.113444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab880f8b03e'
down_revision: Union[str, Sequence[str], None] = '0c52f02cc87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_cars_user_plate_active', 'cars', ['user_id', 'plate'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_cars_user_plate_active', table_name='cars', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('cars')
    # ### end Alembic commands ###
