"""add spot schedules table

Revision ID: d4770c942b3c
Revises: 956b8d573845
Create Date: 2026-09-25 14:53:54.010386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4770c942b3c'
down_revision: Union[str, Sequence[str], None] = '956b8d573845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('spot_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='day_of_week'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id', 'day_of_week', 'start_time', 'end_time', name='uq_schedule_spot_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_schedule')
    # ### end Alembic commands ###
