"""add reservations table

Revision ID: d4fdcb484196
Revises: 3795dae0e113
Create Date: 2026-09-25 15:13:26.738598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4fdcb484196'
down_revision: Union[str, Sequence[str], None] = '3795dae0e113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for the GiST equality operator class on spot_id used by the
    # exclusion constraint below.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('spot_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='reservation_status'), server_default='CONFIRMED', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    postgresql.ExcludeConstraint((sa.column('spot_id'), '='), (sa.text('tsrange(start_at, end_at)'), '&&'), where=sa.text("status = 'CONFIRMED'"), using='gist', name='no_overlapping_confirmed_reservations'),
    sa.CheckConstraint('end_at > start_at', name='ck_reservation_end_after_start'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
